### ISSUE TITLE
Setting a default value of 1 for a writeable bit in misa not allowed

### ISSUE THREAD

**Issue by dthakkar-ventana** [riscv/riscv-config#15]
With respect to the misa register, the SchemaValidator doesn't allow for setting a default value of "1" for a writable bit. That conflicts with what section 3.1 suggests:
> At reset, the Extensions field should contain the maximal set of supported extensions

For example, if an implementation supports the "M" extension but wants to keep it optional for M mode to enable it, the corresponding bit would need to be set to 1 in both the default and bitmask fields. That'd cause SchemaValidator to complain based on the three-way XOR between ISA string, default value and bitmask value of "Extensions" field of misa register.

Rather than a three-way XOR, there should be these separate checks:
The bitmask value must be a subset of what is specified in the ISA string since only implemented extensions can be enabled/disabled.
The default value must be a subset of what is specified in the ISA string since no bit is allowed to be set unless the extension is implemented.
A bitwise OR of the bitmask value and the default value must equal the value specified in the ISA string since each bit must either be hardwired to 1 (bitmask=0 and default=1) or it must be writable (bitmask=1 and default=don't care).
The default value should (not must) be equivalent to what is specified in the ISA string.  Since this is not a strict requirement, perhaps there is nothing to check.

**Comment by Dracarys99** [comment]
The bitmask function is defined in the following way.
For the read only positions, the corresponding bits are cleared (=0) in the mask and the rest of the bits are set (=1).

In the default field the values for the read only bits are given ( = 0 or 1) and the rest of the bits are cleared (=0). 

The values on reset for the writable bits are implicitly 1 on reset.
