### ISSUE TITLE
regarding broken html link for yaml example in riscv config validator documentation

### ISSUE THREAD

**Issue by unclejim843** [riscv/riscv-config#47]
I keep getting error  as hart_ids is not found while running riscv_config

Is there an example input ISA  which takes into account hart_id ?   for simplicity, lets assume single thread with hart id=0. 
When I try to view https://github.com/riscv/riscv_config/blob/master/examples/template_isa.yaml
it does not work

**Comment by unclejim843** [comment]
I want to update that I am no longer getting hart_id error.
but the yaml link is still not working.  it is referenced in the risc-v config validator documentation

**Comment by unclejim843** [comment]
i will close this issue and open just a separate one for the document link

**Comment by neelgala** [comment]
Is this the one you aer talking about : https://riscv-config.readthedocs.io/en/latest/yaml-specs.html

**Comment by unclejim843** [comment]
yes, when I look at
"
An elaborate example of the full-fledge ISA-YAML file can be found here: ISA-YAML"
if I click on the ISA-YAML , it gives me 404. page not found.  same issue in the riscv config.pdf

**Comment by pdonahue-ventana** [comment]
The problem is that note 2 near the top of https://github.com/riscv/riscv-config/blob/master/docs/source/yaml-specs.rst has a dead link.
