### ISSUE TITLE
Define the riscv-config integration flow

### ISSUE THREAD

**Issue by taoliug** [riscv/riscv-config#6]
Here's my understanding of how it works right now
The riscv-config checker will take the platform config and ISA(or CSR) config in YAML format, validate the format, and output YAML files with the full information. We expect this output to be used in verification, ISS config, compliance test etc. Here's my thought of the ideal integration flow: (pseudo code)

```
platform_config = load_platform_config(platform_yaml_file)
isa_config = load_isa_config(isa_yaml_file)

// Expect the checker to generate the validated config handle
valid, validated_isa_config, validate_platform_config = riscv_config_checker(platform_config, isa_config)

// Use the validated configure for various purposes. This could avoid each flow parsing the validated YAML file again.
if valid:
  // Generate CSR test
  gen_csr_test(validated_isa_config)
  // Generate ISS configuration
  gen_iss_config(validate_platform_config, validated_isa_config)
  ....
```

Please let me know your thought about this.

**Comment by neelgala** [comment]
Yes. 
Except that `valid` is not returned. An exception is generated if any illegal spec is detected.

You can find similar usage of the current riscv-config : [here](https://github.com/riscv/riscv-compliance/blob/08c0660722fff77977e314b1b0de1725518c8d21/riscv-ovpsim/config-yaml/main.py#L94-L100)

riscv-config is already packaged via pypi so you can install it using pip and directly import and use it in your python program as shown in the above link

**Comment by taoliug** [comment]
Looks good, thanks

**Comment by taoliug** [comment]
Just want to confirm one more thing. Does the ovpsim script need to parse the validated YAML? or the extracted data structure from the checker? Seems like the ovpsim script is taking YAML as input. Is the script leveraging any common parser?

**Comment by Dracarys99** [comment]
After checking the data is dumped into "_checked" files into the work directory. The ovpsim script currently takes these files to further process them into the overrides. The parser would be present as an import for implementations to use. Currently there is no common parser necessary.

**Comment by taoliug** [comment]
OK, got it, maybe the current format is simple enough so that common parser is not necessary. With the new format, I believe we do need something to parse the WARL specification.

**Comment by simon5656** [comment]
Tao
you can look here at the initial ovpsim integration. we just write a main that calls the appropriate functions/classes
https://github.com/riscv/riscv-ovpsim/tree/master/config-yaml
we just read in the user written yaml, validate it, and read the file it created  (and re-validate) and then write out the OVPsim config file
Simon

________________________________

**Comment by taoliug** [comment]
Thanks Simon, do you plan to support the new WARL specification? I am not sure if ovpsim supports override like that.

**Comment by neelgala** [comment]
@simon5656 .. could you confirm if the new WARL format is convenient enough for generating overrides for ovpsim?
