### ISSUE TITLE
readonly vs hardwired readonly

### ISSUE THREAD

**Issue by neelgala** [riscv/riscv-config#7]
In the new proposal, `type` can take 3 values: RO, WLRL and WARL.
RO refers to a hardwired read-only, which means that this field will always return the same value.

However, the spec defines fields like `SD` in mstatus which are readonly to the user but the value of the field depends on other micro-architectural state like `xs` and `fs`. So this doesn't fall under the RO category defined above neither is it WARL since it writes are not allowed to his field. 

What should the type field be for such fields?
we can redefined RO to be ro_constant and define SD as ro_variable. 

ro_constant will always respond with the same value.
ro_variable will however respond with different values but should we capture the function it depends on?

**Comment by neelgala** [comment]
@simon5656 @eroom1966 @taoliug any views on this?

**Comment by taoliug** [comment]
I think RO_VARIABLE sounds good to me. I think it's hard to accurately describe the dependency. There could be other similar registers like performance counters, which is RO but can be updated by the processor. From the verification perspective, this type of register needs to be modeled case by case.

**Comment by neelgala** [comment]
okay good.. maybe for now i'l leave ro_variable as a boolean field only
Later versions could take an effort to formalize the dependency if there are sufficient use-cases and requirements.
